/*
 * This file is part of LiquidBounce (https://github.com/CCBlueX/LiquidBounce)
 *
 * Copyright (c) 2015 - 2026 CCBlueX
 *
 * LiquidBounce is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LiquidBounce is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LiquidBounce. If not, see <https://www.gnu.org/licenses/>.
 */
package net.ccbluex.liquidbounce.features.baritone.adapter

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class NativeSettingsFileParserTest {

    @Test
    fun `parses upstream syntax while retaining unknown names and spaced values`() {
        val result = NativeSettingsFileParser.parse(
            sequenceOf(
                "# generated by Baritone",
                "// another comment",
                "",
                "allowBreak false",
                "FutureSetting   value with spaces  ",
            )
        )

        assertEquals(
            listOf(
                NativeSettingLine("allowBreak", "allowbreak", "false", 4),
                NativeSettingLine("FutureSetting", "futuresetting", "value with spaces", 5),
            ),
            result.settings,
        )
        assertTrue(result.warnings.isEmpty())
    }

    @Test
    fun `reports malformed non-comment lines without discarding valid settings`() {
        val result = NativeSettingsFileParser.parse(
            sequenceOf(
                "allowSprint true",
                "missing-value",
                "    ",
                "allowPlace false",
            )
        )

        assertEquals(listOf("allowsprint", "allowplace"), result.settings.map(NativeSettingLine::normalizedName))
        assertEquals(1, result.warnings.size)
        assertTrue("line 2" in result.warnings.single())
    }
}
