export const MENU_READY_DELAY_MS = 80;
export const MENU_TRANSITION_MS = 180;
export const MENU_VERTICAL_OFFSET_PX = 48;
export const MENU_HORIZONTAL_OFFSET_PX = 260;

export const TITLE_BUTTON_TRANSITION_MS = 220;
export const TITLE_BUTTON_STAGGER_MS = 35;
export const TITLE_BUTTON_OFFSET_PX = 280;
export const TITLE_BUTTON_SWITCH_DELAY_MS = TITLE_BUTTON_TRANSITION_MS + TITLE_BUTTON_STAGGER_MS * 3;
